import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../app.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class HomeApp extends StatelessWidget {
  const HomeApp({super.key});

  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations(
        [
          DeviceOrientation.portraitUp,
          DeviceOrientation.portraitDown,
        ],
    );
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Home(),
        ]),
      ),
    );
  }
}


class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 411,
          height: 731,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFFCFFFA),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 25,
                top: 57,
                child: Container(
                  width: 361,
                  height: 547,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 267,
                          height: 54,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 59,
                                top: 20,
                                child: Text(
                                  'Let’s get recycling!',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 25,
                                    fontFamily: 'Proxima Nova',
                                    fontWeight: FontWeight.w600,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 4,
                                child: Text(
                                  'Welcome back, Sarah',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Proxima Nova',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 54,
                                  height: 54,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/54x54"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(
                                      side: BorderSide(width: 1, color: Color(0xFFF6F6F6)),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ), //Welcome, lets get recycling
                      Positioned(
                        left: 310.19,
                        top: 12.95,
                        child: Container(
                          width: 50.81,
                          height: 21.05,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 21.81,
                                top: 5.05,
                                child: Text(
                                  '300',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 16,
                                    fontFamily: 'Proxima Nova',
                                    fontWeight: FontWeight.w500,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ), //300
                      Positioned(
                        left: 6,
                        top: 74,
                        child: Container(
                          width: 349,
                          height: 65,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 145,
                                  height: 65,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 145,
                                          height: 65,
                                          decoration: ShapeDecoration(
                                            color: Color(0xFFFCFFFA),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(10),
                                            ),
                                            shadows: [
                                              BoxShadow(
                                                color: Color(0x3F000000),
                                                blurRadius: 4,
                                                offset: Offset(0, 4),
                                                spreadRadius: 0,
                                              )
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 46,
                                        top: 30,
                                        child: Text(
                                          'Earn',
                                          style: TextStyle(
                                            color: Color(0xFF3C9040),
                                            fontSize: 20,
                                            fontFamily: 'Proxima Nova',
                                            fontWeight: FontWeight.w600,
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 4,
                                        top: 14.72,
                                        child: Container(
                                          width: 40,
                                          height: 38.86,
                                          child: Stack(children: [
                                            //,
                                          ]),
                                        ),
                                      ),
                                      Positioned(
                                        left: 107,
                                        top: 48,
                                        child: Transform(
                                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                                          child: Container(
                                            width: 30,
                                            height: 30,
                                            padding: const EdgeInsets.only(
                                              top: 10.74,
                                              left: 7.50,
                                              right: 7.50,
                                              bottom: 10,
                                            ),
                                            decoration: BoxDecoration(
                                              boxShadow: [
                                                BoxShadow(
                                                  color: Color(0xBFFFFFFF),
                                                  blurRadius: 5,
                                                  offset: Offset(0, 0),
                                                  spreadRadius: 0,
                                                )
                                              ],
                                            ),
                                            child: Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.center,
                                              crossAxisAlignment: CrossAxisAlignment.center,
                                              children: [
                                                //,
                                              ],
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 160,
                                top: 0,
                                child: Container(
                                  width: 189,
                                  height: 65,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 189,
                                          height: 65,
                                          decoration: ShapeDecoration(
                                            color: Color(0xFFFCFFFA),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(10),
                                            ),
                                            shadows: [
                                              BoxShadow(
                                                color: Color(0x3F000000),
                                                blurRadius: 4,
                                                offset: Offset(0, 4),
                                                spreadRadius: 0,
                                              )
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 12,
                                        top: 14.72,
                                        child: Container(
                                          width: 40,
                                          height: 38.86,
                                          child: Stack(children: [
                                            //,
                                          ]),
                                        ),
                                      ),
                                      Positioned(
                                        left: 57,
                                        top: 30,
                                        child: Text(
                                          'Redeem',
                                          style: TextStyle(
                                            color: Color(0xFF3C9040),
                                            fontSize: 20,
                                            fontFamily: 'Proxima Nova',
                                            fontWeight: FontWeight.w600,
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 151,
                                        top: 48,
                                        child: Transform(
                                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                                          child: Container(
                                            width: 30,
                                            height: 30,
                                            padding: const EdgeInsets.only(
                                              top: 10.74,
                                              left: 7.50,
                                              right: 7.50,
                                              bottom: 10,
                                            ),
                                            decoration: BoxDecoration(
                                              boxShadow: [
                                                BoxShadow(
                                                  color: Color(0xBFFFFFFF),
                                                  blurRadius: 5,
                                                  offset: Offset(0, 0),
                                                  spreadRadius: 0,
                                                )
                                              ],
                                            ),
                                            child: Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.center,
                                              crossAxisAlignment: CrossAxisAlignment.center,
                                              children: [
                                                //,
                                              ],
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ), //Earn and Redeem
                      Positioned(
                        left: 0,
                        top: 169,
                        child: Container(
                          width: 361,    //361
                          height: 169,    //169
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 361,
                                  height: 169,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFE8FAD3),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 0.50, color: Color(0xFF94E74A)),
                                      borderRadius: BorderRadius.circular(20),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 70,
                                top: 20,
                                child: Text(
                                  'This week, you’ve recycled:',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 18,
                                    fontFamily: 'Proxima Nova',
                                    fontWeight: FontWeight.w600,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 53,
                                top: 54,
                                child: Container(
                                  width: 260,
                                  height: 57,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 5,
                                        child: Container(
                                          width: 255,
                                          height: 47,
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Container(
                                                width: 47,
                                                height: 47,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 47,
                                                        height: 47,
                                                        decoration: ShapeDecoration(
                                                          color: Color(0xFFFCFFFA),
                                                          shape: OvalBorder(),
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 7,
                                                      top: 7,
                                                      child: Container(
                                                        width: 34,
                                                        height: 34,
                                                        padding: const EdgeInsets.only(
                                                          top: 6.46,
                                                          left: 2.12,
                                                          right: 3.54,
                                                          bottom: 6.46,
                                                        ),
                                                        child: Row(
                                                          mainAxisSize: MainAxisSize.min,
                                                          mainAxisAlignment: MainAxisAlignment.center,
                                                          crossAxisAlignment: CrossAxisAlignment.center,
                                                          children: [
                                                            Container(
                                                              width: 28.33,
                                                              height: 21.08,
                                                              child: Stack(children: [
                                                                //,
                                                              ]),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                              const SizedBox(width: 57),
                                              Container(
                                                width: 47,
                                                height: 47,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 47,
                                                        height: 47,
                                                        decoration: ShapeDecoration(
                                                          color: Color(0xFFFCFFFA),
                                                          shape: OvalBorder(),
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 6,
                                                      top: 6,
                                                      child: Container(
                                                        width: 35,
                                                        height: 35,
                                                        clipBehavior: Clip.antiAlias,
                                                        decoration: BoxDecoration(),
                                                        child: Stack(children: [
                                                          //,
                                                        ]),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                              const SizedBox(width: 57),
                                              Container(
                                                width: 47,
                                                height: 47,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 47,
                                                        height: 47,
                                                        decoration: ShapeDecoration(
                                                          color: Color(0xFFFCFFFA),
                                                          shape: OvalBorder(),
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 7,
                                                      top: 7,
                                                      child: Container(
                                                        width: 33,
                                                        height: 33,
                                                        padding: const EdgeInsets.symmetric(horizontal: 9.17, vertical: 3.44),
                                                        child: Row(
                                                          mainAxisSize: MainAxisSize.min,
                                                          mainAxisAlignment: MainAxisAlignment.center,
                                                          crossAxisAlignment: CrossAxisAlignment.center,
                                                          children: [
                                                            Container(
                                                              width: 14.65,
                                                              height: 26.12,
                                                              child: Stack(children: [
                                                                //,
                                                              ]),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 232,
                                        top: 0,
                                        child: Container(
                                          width: 28,
                                          height: 56.99,
                                          decoration: BoxDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://via.placeholder.com/28x57"),
                                              fit: BoxFit.fill,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 99,
                                        top: 0,
                                        child: Container(
                                          width: 57,
                                          height: 57,
                                          decoration: BoxDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://via.placeholder.com/57x57"),
                                              fit: BoxFit.fill,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 24,
                                        top: 0,
                                        child: Container(
                                          width: 26.26,
                                          height: 20.53,
                                          decoration: BoxDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://via.placeholder.com/26x21"),
                                              fit: BoxFit.fill,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 172,
                                top: 115,
                                child: Text(
                                  '5/5',
                                  style: TextStyle(
                                    color: Color(0xFF010900),
                                    fontSize: 12,
                                    fontFamily: 'Proxima Nova',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 277,
                                top: 115,
                                child: Text(
                                  '1/2',
                                  style: TextStyle(
                                    color: Color(0xFF010900),
                                    fontSize: 12,
                                    fontFamily: 'Proxima Nova',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 68,
                                top: 115,
                                child: Text(
                                  '2/5',
                                  style: TextStyle(
                                    color: Color(0xFF010900),
                                    fontSize: 12,
                                    fontFamily: 'Proxima Nova',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 48,
                                top: 129,
                                child: Text(
                                  'Cardboard',
                                  style: TextStyle(
                                    color: Color(0xFF010900),
                                    fontSize: 12,
                                    fontFamily: 'Proxima Nova',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 162,
                                top: 129,
                                child: Text(
                                  'Bottles',
                                  style: TextStyle(
                                    color: Color(0xFF010900),
                                    fontSize: 12,
                                    fontFamily: 'Proxima Nova',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 271,
                                top: 129,
                                child: Text(
                                  'Cans',
                                  style: TextStyle(
                                    color: Color(0xFF010900),
                                    fontSize: 12,
                                    fontFamily: 'Proxima Nova',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ), //This week
                      Positioned(
                        left: 0,
                        top: 378,
                        child: Container(
                          height: 150,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  'Weekly Challenge',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 25,
                                    fontFamily: 'Proxima Nova',
                                    fontWeight: FontWeight.w600,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 44,
                                child: Container(
                                  width: 361,
                                  height: 106,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 361,
                                          height: 106,
                                          decoration: ShapeDecoration(
                                            color: Color(0xFFE8FAD3),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(10),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 24,
                                        top: 20,
                                        child: Text(
                                          'Repurpose 5 glass jars',
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 18,
                                            fontFamily: 'Proxima Nova',
                                            fontWeight: FontWeight.w500,
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 26,
                                        top: 46,
                                        child: Text(
                                          '3/5 jars',
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 18,
                                            fontFamily: 'Proxima Nova',
                                            fontWeight: FontWeight.w600,
                                            letterSpacing: 0.90,
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 271,
                                        top: 15,
                                        child: Container(
                                          width: 73.29,
                                          height: 75.49,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 13,
                                                top: 70,
                                                child: Container(
                                                  width: 40,
                                                  height: 5,
                                                  decoration: ShapeDecoration(
                                                    color: Color(0x99010900),
                                                    shape: OvalBorder(),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 31.93,
                                                top: 21.63,
                                                child: Transform(
                                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.26),
                                                  child: Container(
                                                    width: 42.84,
                                                    height: 44.22,
                                                    decoration: BoxDecoration(
                                                      image: DecorationImage(
                                                        image: NetworkImage("https://via.placeholder.com/43x44"),
                                                        fit: BoxFit.cover,
                                                      ),
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 3.88,
                                                child: Transform(
                                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.10),
                                                  child: Container(
                                                    width: 39.78,
                                                    height: 62.38,
                                                    decoration: BoxDecoration(
                                                      image: DecorationImage(
                                                        image: NetworkImage("https://via.placeholder.com/40x62"),
                                                        fit: BoxFit.cover,
                                                      ),
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 26,
                                        top: 74,
                                        child: Container(
                                          width: 251,
                                          height: 12,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 251,
                                                  height: 12,
                                                  decoration: ShapeDecoration(
                                                    color: Color(0xFFFCFFFA),
                                                    shape: RoundedRectangleBorder(
                                                      borderRadius: BorderRadius.circular(10),
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 143,
                                                  height: 12,
                                                  decoration: ShapeDecoration(
                                                    color: Color(0xFF94E74A),
                                                    shape: RoundedRectangleBorder(
                                                      borderRadius: BorderRadius.circular(10),
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ), //Weekly Challenge
                      Positioned(
                        left: 0,
                        top: 563,
                        child: Container(
                          height: 319,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  'Next Collection',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 24,
                                    fontFamily: 'Proxima Nova',
                                    fontWeight: FontWeight.w600,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 44,
                                child: Container(
                                  width: 361,
                                  height: 275,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 361,
                                          height: 275,
                                          decoration: ShapeDecoration(
                                            color: Color(0xFFFCFFFA),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(20),
                                            ),
                                            shadows: [
                                              BoxShadow(
                                                color: Color(0x994CAF50),
                                                blurRadius: 5,
                                                offset: Offset(0, 1),
                                                spreadRadius: 0,
                                              )
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 30,
                                        top: 22,
                                        child: Text.rich(
                                          TextSpan(
                                            children: [
                                              TextSpan(
                                                text: 'Tuesday, ',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 28,
                                                  fontFamily: 'Proxima Nova',
                                                  fontWeight: FontWeight.w700,
                                                  height: 1.43,
                                                ),
                                              ),
                                              TextSpan(
                                                text: 'August 15',
                                                style: TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 28,
                                                  fontFamily: 'Proxima Nova',
                                                  fontWeight: FontWeight.w700,
                                                  height: 1,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 23,
                                        top: 117,
                                        child: Container(
                                          width: 315,
                                          height: 110,
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Container(
                                                width: 97,
                                                height: 110,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 97,
                                                        height: 110,
                                                        decoration: ShapeDecoration(
                                                          color: Color(0xFF4CAF50),
                                                          shape: RoundedRectangleBorder(
                                                            borderRadius: BorderRadius.circular(10),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 9,
                                                      top: 15,
                                                      child: Container(
                                                        width: 79,
                                                        height: 79,
                                                        decoration: BoxDecoration(
                                                          image: DecorationImage(
                                                            image: NetworkImage("https://via.placeholder.com/79x79"),
                                                            fit: BoxFit.fill,
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                              const SizedBox(width: 12),
                                              Container(
                                                width: 97,
                                                height: 110,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 97,
                                                        height: 110,
                                                        decoration: ShapeDecoration(
                                                          color: Color(0xFF4CAF50),
                                                          shape: RoundedRectangleBorder(
                                                            borderRadius: BorderRadius.circular(10),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 26,
                                                      top: 14.15,
                                                      child: Container(
                                                        width: 45.62,
                                                        height: 81.95,
                                                        decoration: BoxDecoration(
                                                          image: DecorationImage(
                                                            image: NetworkImage("https://via.placeholder.com/46x82"),
                                                            fit: BoxFit.fill,
                                                          ),
                                                          boxShadow: [
                                                            BoxShadow(
                                                              color: Color(0xFF000000),
                                                              blurRadius: 4,
                                                              offset: Offset(0, 4),
                                                              spreadRadius: 0,
                                                            )
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                              const SizedBox(width: 12),
                                              Container(
                                                width: 97,
                                                height: 110,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 97,
                                                        height: 110,
                                                        decoration: ShapeDecoration(
                                                          color: Color(0xFF4CAF50),
                                                          shape: RoundedRectangleBorder(
                                                            borderRadius: BorderRadius.circular(10),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 23,
                                                      top: 18,
                                                      child: Container(
                                                        width: 52,
                                                        height: 74,
                                                        decoration: BoxDecoration(
                                                          image: DecorationImage(
                                                            image: NetworkImage("https://via.placeholder.com/52x74"),
                                                            fit: BoxFit.fill,
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 30,
                                        top: 72,
                                        child: Container(
                                          width: 24,
                                          height: 24,
                                          padding: const EdgeInsets.all(3),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 18,
                                                height: 18,
                                                decoration: BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage("https://via.placeholder.com/18x18"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 59,
                                        top: 70,
                                        child: Text(
                                          'Taken out',
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 20,
                                            fontFamily: 'Proxima Nova',
                                            fontWeight: FontWeight.w400,
                                            height: 1.40,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ), //Next Collection
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 3,
                top: 604,
                child: Container(
                  width: 405,
                  height: 127,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 405,
                        height: 127,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 40,
                              child: Container(
                                width: 405,
                                height: 87,
                                decoration: ShapeDecoration(
                                  color: Color(0xFFFCFFFA),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(20),
                                  ),
                                  shadows: [
                                    BoxShadow(
                                      color: Color(0xFFE6E6E6),
                                      blurRadius: 30,
                                      offset: Offset(0, -1),
                                      spreadRadius: 1,
                                    )
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 162,
                              top: 0,
                              child: Container(
                                width: 80,
                                height: 80,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 80,
                                        height: 80,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFF94E74A),
                                          shape: OvalBorder(),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 17,
                                      top: 17,
                                      child: Container(
                                        width: 46,
                                        height: 46,
                                        padding: const EdgeInsets.symmetric(horizontal: 3.83, vertical: 4.63),
                                        decoration: BoxDecoration(color: Color(0xFF94E74A)),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          children: [
                                            //,
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 12,
                              top: 51,
                              child: Opacity(
                                opacity: 0.60,
                                child: Container(
                                  width: 68,
                                  height: 68,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFE8FAD3),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 26,
                              top: 54,
                              child: Container(
                                width: 40,
                                height: 40,
                                child: Stack(children: [
                                  //,
                                ]),
                              ),
                            ),
                            Positioned(
                              left: 22,
                              top: 94,
                              child: Text(
                                'Home',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 18,
                                  fontFamily: 'Proxima Nova',
                                  fontWeight: FontWeight.w500,
                                ),
                              ),
                            ),
                            Positioned(
                              left: 106,
                              top: 66,
                              child: Container(
                                width: 36,
                                height: 36,
                                child: Stack(children: [
                                  //,
                                ]),
                              ),
                            ),
                            Positioned(
                              left: 182,
                              top: 64,
                              child: Opacity(
                                opacity: 0,
                                child: Container(
                                  width: 40,
                                  height: 40,
                                  padding: const EdgeInsets.symmetric(horizontal: 3.33, vertical: 4.03),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      //,
                                    ],
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 262,
                              top: 66,
                              child: Container(
                                width: 36,
                                height: 36,
                                child: Stack(children: [
                                  //,
                                ]),
                              ),
                            ),
                            Positioned(
                              left: 338,
                              top: 64,
                              child: Container(
                                width: 40,
                                height: 40,
                                child: Stack(children: [
                                  //,
                                ]),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 0,
                child: Container(
                  width: 390,
                  height: 47,
                  padding: const EdgeInsets.only(
                    top: 15.33,
                    left: 35.33,
                    right: 17,
                    bottom: 12.67,
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.end,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        '9:41',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color(0xFF2F2F2F),
                          fontSize: 15.66,
                          fontFamily: 'SF Pro Text',
                          fontWeight: FontWeight.w600,
                          letterSpacing: -0.28,
                        ),
                      ),
                      Container(
                        width: 73,
                        height: 16,
                        padding: const EdgeInsets.only(
                          top: 2,
                          left: 2.33,
                          right: 1.34,
                          bottom: 1.67,
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 17,
                              height: 11.33,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/17x11"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            Container(
                              width: 16.71,
                              height: 12,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/17x12"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            Container(
                              width: 25,
                              height: 12,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Container(
                                    width: 18.66,
                                    height: 8,
                                    decoration: ShapeDecoration(
                                      color: Color(0xFF2F2F2F),
                                      shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(1.33),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
